import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navbar } from '@/components/blocks/bars/NavBar';
import { SessionProvider } from '@/context/Sessioncontext';
import UILayout from './ui-layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <UILayout>{children}</UILayout>
        </SessionProvider>
      </body>
    </html>
  );
}
